### PR TITLE
Correct length to endof in SubString call

### LINKED ISSUE #470: Doctest failure diff not showing up right on current Julia master
ref the original thing I posted at https://github.com/JuliaLang/julia/pull/21633 which I'm about to delete

```
Documenter: running document checks.
 > running doctests.
=====[Test Error]==============================

> File: strings/util.jl

> Code block:

``jldoctest # edited out the third ` for github highlighting sake
julia> ascii("abcdeγfgh")
ERROR: ArgumentError: invalid ASCII at index 6 in "abcdeγfgh"
Stacktrace:
 [1] ascii(::String) at ./strings/util.jl:475

julia> ascii("abcdefgh")
"abcdefgh"
`` # edited out the third ` for github highlighting sake

> Subexpression:

    ascii("abcdeγfgh")

> Output Diff:

ERROR: ArgumentError: invalid ASCII at index 6 in "abcdeγfgh"
Stacktrace:
 [1] ascii(::String) at ./strings/util.jl:47

=====[End Error]===============================
 > checking footnote links.
Documenter: populating indices.
ERROR: LoadError: `makedocs` encountered an error. Terminating build
Stacktrace:
 [1] runner(::Type{Documenter.Builder.RenderDocument}, ::Documenter.Documents.Document) at /home/tkelman2/Julia/julia-0.6/doc/deps/v0.6/Documenter/src/Builder.jl:202
 [2] dispatch(::Type{Documenter.Builder.DocumentPipeline}, ::Documenter.Documents.Document) at /home/tkelman2/Julia/julia-0.6/doc/deps/v0.6/Documenter/src/Selectors.jl:164
 [3] cd(::Documenter.##2#3{Documenter.Documents.Document}, ::String) at ./file.jl:70
 [4] #makedocs#1(::Bool, ::Array{Any,1}, ::Function) at /home/tkelman2/Julia/julia-0.6/doc/deps/v0.6/Documenter/src/Documenter.jl:198
 [5] (::Documenter.#kw##makedocs)(::Array{Any,1}, ::Documenter.#makedocs) at ./<missing>:0
 [6] include_from_node1(::String) at ./loading.jl:539
 [7] include(::String) at ./sysimg.jl:14
 [8] process_options(::Base.JLOptions) at ./client.jl:305
 [9] _start() at ./client.jl:371
```

this is from `make docs && make -C doc doctest` at https://github.com/JuliaLang/julia/commit/a0c142950562bf81e048944b9c9714a9f6af7a89

### PR DESCRIPTION
**Pull request by bkamins**
`length` will fail on multibyte `Char`.
E.g.
```
x = "∀∀∀"
length(x) # 3 - results incorrect indexing
endof(x) # 7 - correct index of last Char
```

This is part of the fix needed for https://github.com/JuliaLang/julia/pull/22511.

Fixes #470.

### CODE REVIEW

**Comment by mortenpi** [comment]
Any ideas whether this might fix #470?

**Comment by bkamins** [comment]
@mortenpi The old code was dropping characters for multibyte `Char`s in strings (as @tkelman suggested in #470).
The reason is that `length(s)` is not the index for the last character in a string. After https://github.com/JuliaLang/julia/pull/22511 this causes fail to build at all as this PR enforces strict checking of indexing into `SubString` (currently it silently returned wrong result).

**Comment by nalimilan** [comment]
So the stricter indexing rules have already caught one bug? That's great news!

File: src/Utilities/TextDiff.jl [hunk 1]
```diff
@@ -48,7 +48,7 @@ function splitby(reg::Regex, text::AbstractString)
         push!(out, SubString(text, last, each.match.offset + each.match.endof))
         last = each.match.endof + each.offset
     end
-    local laststr = SubString(text, last, length(text))
+    local laststr = SubString(text, last, endof(text))
```
Comment (nalimilan) [inline src/Utilities/TextDiff.jl]: `endof(text)` is redundant, right?

Comment (bkamins) [inline src/Utilities/TextDiff.jl]: right 😄

**Comment by mortenpi** [comment]
LGTM, thanks! I can confirm that it fixes #470 as well. I'll try to put out a (long overdue) patch release with this one shortly so that JuliaLang/julia#22511 could be merged.
