### PR TITLE
Drop SSH keys from env when running external commands

### LINKED ISSUE #1958: Reporting process errors leaks DOCUMENTER_KEY
Documenter.jl currently wraps `git` commands in `try`/`catch`, reporting the failed process exception when something goes wrong. This is very bad, because it may leak the DOCUMENTER_KEY environment variable that the user has set:

```
Initialized empty Git repository in /tmp/jl_SChxvR/.git/
Load key "/var/lib/buildkite-agent/builds/gpuci-16/julialang/scimlsensitivity-dot-jl/docs/.documenter": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
 
Please make sure you have the correct access rights
and the repository exists.
┌ Error: Git failed to fetch git@github.com:SciML/SciMLSensitivity.jl.git
│ This can be caused by a DOCUMENTER_KEY variable that is not correctly set up.
│ Make sure that the environment variable is properly set up as a Base64-encoded string
│ of the SSH private key. You may need to re-generate the keys with DocumenterTools.
└ @ Documenter ~/.cache/julia-buildkite-plugin/depots/ea52448d-f230-4619-b27a-2d98107bd215/packages/Documenter/yf96B/src/Documenter.jl:652
┌ Error: Failed to push:
│   exception =
│    failed process: Process(setenv(`/usr/bin/git fetch upstream`,["DOCUMENTER_KEY=XXXXXXXX", "PATH=YYYY", ...]), ProcessExited(128)) [128]
```

It would be best to not just dump these exceptions to STDOUT (even if you scrub DOCUMENTER_KEY it may contain other sensitive information). In addition, it's probably best to scrub DOCUMENTER_KEY from the environment as soon as its parsed by Documenter.jl to prevent it from leaking to any other spawned commands.

cc @ChrisRackauckas

### PR DESCRIPTION
**Pull request by fredrikekre**
Should fix #1958.

### CODE REVIEW

File: src/Documenter.jl [hunk 1]
```diff
@@ -764,6 +769,8 @@ function git_push(
             isfile(keyfile) && rm(keyfile)
         end
     else # authentication_method(deploy_config) === HTTPS
+        # Remove SSH keys if existing
+        documenter_key_delete!()
```
Comment (mortenpi) [inline src/Documenter.jl:773]: I don't think it's necessarily an issue, but does this break the case where you'd call `deploydocs` multiple times?

**Review by mortenpi — COMMENTED** [review]
It wouldn't save us from these cases though (there are probably more)?

https://github.com/JuliaDocs/Documenter.jl/blob/70017e05f5c0297774c78e0774098577c6885a55/src/Utilities/Utilities.jl#L777

In general, I think doing something like this is worth it, but I think in addition we should also fix the places where we print the `Cmd` objects in errors.

https://github.com/JuliaDocs/Documenter.jl/blob/70017e05f5c0297774c78e0774098577c6885a55/src/Utilities/Utilities.jl#L431

File: src/Documenter.jl (hunk 1 above)
Comment (fredrikekre) [reply src/Documenter.jl:773]: Yea I guess, but will that matter in practice?

**Comment by fredrikekre** [comment]
Perhaps we should also recommend splitting it up in two steps and only provide the secret in the yml file to the deploydocs part.

File: src/Documenter.jl (hunk 1 above)
Comment (mortenpi) [reply src/Documenter.jl:773]: I think we could live with it, but OTOH someone might create a weird setup where they deploy to multiple places or something like that. How doable do you think it would be to wrap everything in a big `withenv` instead?

**Comment by mortenpi** [comment]
> 
Perhaps we should also recommend splitting it up in two steps and only provide the secret in the yml file to the deploydocs part.

This was also mentioned here: https://github.com/JuliaDocs/Documenter.jl/issues/1959#issuecomment-1264887351

I don't think it's a bad idea. The only question I have though is whether we should then move towards having more of the decision whether to deploy or not in the CI config, as opposed to decided by `deploydocs`?

File: src/Documenter.jl (hunk 1 above)
Comment (fredrikekre) [reply src/Documenter.jl:773]: Yea maybe that is the easiest option.

**Review by mortenpi — APPROVED** [review]
LGTM
