### PR TITLE
Make sure we have LF line endings only.

### LINKED ISSUE #749: Totally weird parsing/unknown problem...
I am facing some parsing problems when trying to use PyPlot to plot and save figures to use in my documentation...

I am sorry, I don't really know how to make a MWE because I got no clue where the problem is. **The documentation example works fine for me**.

```
```@example 8
using PyPlot, DynamicalBilliards
b = billiard_polygon(6, 1)
a = Antidot([0.0,0.0], 0.5)
bd = Billiard(b.obstacles..., a)

figure()
plot_obstacle!(bd[end])
plot_obstacle!(bd[1])
plot_obstacle!(bd[2]; linewidth = 3.0, linestyle = "dashed", color = (0.0, 0.5, 0.5))

PyPlot.xlim(-1, 1); PyPlot.ylim(-1, 1);

savefig("obstacles_example.svg"); nothing # hide
```
Gives error:
```
 !! failed to run code block.

UndefVarError(:igure) [src\visualizing.md]
```
*please note that this error is not from my side; copy-pasting this block to the REPL is fine*

On the other side, these:
```
```@example 8
plot_billiard(bd)
savefig("billiard_example.svg"); nothing # hide
```

```
```@example 8
p = randominside(bd)
plot_particle!(p)
# Plot one more particle with purple color,
# pentagon shape and bigger size (default is s=30):
p2 = randominside(bd)
plot_particle!(p2; color=(0.5, 0, 0.8), marker="p", s=60.0)
savefig("particles_example.svg"); nothing # hide
```

parse fine, they do their figures, do their plottings, they save their figures and all is cool. **Not only that, but even though the initial block failed to run correctly, the `using DynamicalBilliards, PyPlot` statement took effect, since it is used in the later blocks**.

Let me know if I can do more to help. If you want to run these code blocks you have to checkout the branch `namefield` of `DynamicalBilliards`. These examples are in the `docs/visualizing.md` file.

### LINKED ISSUE #790: ERROR: UndefVarError:  not defined
Hello,

I'm currently working on https://github.com/JuliaCollections/DataStructures.jl/issues/360 and trying to add `@repl` / `@setup` macros for examples in `default_dict.md`

the following minimal file 

    # DefaultDict and DefaultOrderedDict

    ```@setup DataStructures
    using DataStructures
    ```

    ```@repl DataStructures
    dd = DefaultDict{AbstractString, Vector{Int}}(Vector{Int})

    push!(dd["A"], 1)

    push!(dd["B"], 2)

    dd
    ```

is badly rendered with Julia 0.7

```
julia> dd = DefaultDict{AbstractString, Vector{Int}}(Vector{Int})
DefaultDict{AbstractString,Array{Int64,1},DataType} with 0 entries

julia> p
┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0
ERROR: UndefVarError:  not defined

julia> ush!(dd["A"], 1)
ERROR: UndefVarError: ush! not defined

julia> p
┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0
ERROR: UndefVarError:  not defined

julia> ush!(dd["B"], 2)
ERROR: UndefVarError: ush! not defined

julia> d
┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0
ERROR: UndefVarError:  not defined

julia> d
ERROR: UndefVarError: d not defined
```

Any idea?

Thanks

### PR DESCRIPTION
**Pull request by fredrikekre**
fix #749, fix #790

### CODE REVIEW

**Comment by fredrikekre** [comment]
@scls19fr can you try this branch? You can `pkg> add Documenter#fe/fix-parsing` from the Pkg REPL.

**Comment by fredrikekre** [comment]
@Datseris maybe you can try this branch too, if you still can reproduce this problem.

**Comment by Datseris** [comment]
Im on it.

**Comment by scls19fr** [comment]
LGTM. Thanks @fredrikekre for this fix

File: src/Utilities/Utilities.jl [hunk 1]
```diff
@@ -114,11 +114,11 @@ parsed from.
 The keyword argument `skip = N` drops the leading `N` lines from the input string.
 """
 function parseblock(code::AbstractString, doc, page; skip = 0, keywords = true)
+    # work only with LF line endings internally
+    code = replace(code, "\r\n" => "\n")
     # Drop `skip` leading lines from the code block. Needed for deprecated `{docs}` syntax.
     code = string(code, '\n')
     code = last(split(code, '\n', limit = skip + 1))
-    # Check whether we have windows-style line endings.
-    offset = occursin("\n\r", code) ? 2 : 1
```
Comment (fredrikekre) [inline src/Utilities/Utilities.jl]: I suspect the error was from this beeing `"\n\r"` and not `"\r\n"`, but I figured we might as well just use `"\n"` internally.

**Comment by fredrikekre** [comment]
Perfect, thanks for confirming.

File: src/Utilities/Utilities.jl (hunk 1 above)
Comment (fredrikekre) [reply src/Utilities/Utilities.jl]: And also, this local `code` argument does not leak out of this parser function anyways.

File: src/Utilities/Utilities.jl [hunk 2]
```diff
@@ -114,11 +114,11 @@ parsed from.
 The keyword argument `skip = N` drops the leading `N` lines from the input string.
 """
 function parseblock(code::AbstractString, doc, page; skip = 0, keywords = true)
+    # work only with LF line endings internally
+    code = replace(code, "\r\n" => "\n")
```
Comment (fredrikekre) [inline src/Utilities/Utilities.jl]: Actually, this could be dangerous if someone have `"\r\n"` in a string. Should revert this and let the Julia parser decide this kind of things instead.

**Comment by fredrikekre** [comment]
@Datseris or @scls19fr sorry, but can you check the updated version too? `pkg> up` from the REPL if you still have this branch `pkg> add`ed, otherwise just add again as above.

**Comment by scls19fr** [comment]
It's broken on my side

**Comment by Datseris** [comment]
Hm That's weird @scls19fr . @fredrikekre I can confirm that this is still LGTM on Windows 10. I am also testing it with a documentation that was problematic, i.e. was causing the problems of #749.

**Comment by scls19fr** [comment]
Ok I will remove my .julia folder to double check

**Comment by fredrikekre** [comment]
@scls19fr do you mean that the previous version of this PR worked? It looks like you get different errors now.

**Comment by scls19fr** [comment]
This is because it's not the same part of page (with the minimal md file I mentioned https://github.com/JuliaDocs/Documenter.jl/issues/790#issue-350004634 I get)
```
julia> dd = DefaultDict{AbstractString, Vector{Int}}(Vector{Int})
DefaultDict{AbstractString,Array{Int64,1},DataType} with 0 entries

julia> p
┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0
ERROR: UndefVarError:  not defined

julia> ush!(dd["A"], 1)
ERROR: UndefVarError: ush! not defined

julia> p
┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0
ERROR: UndefVarError:  not defined

julia> ush!(dd["B"], 2)
ERROR: UndefVarError: ush! not defined

julia> d
┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0
ERROR: UndefVarError:  not defined

julia> d
ERROR: UndefVarError: d not defined
```

I think the previous PR was working correctly.
Did you squash commits? Can remember what you changed

**Comment by Datseris** [comment]
This may sound stupid, but I recall from Slack that `add Package#somebranch` always adds the master branch and one has to check out manually via git....?

**Comment by KristofferC** [comment]
`add Package#branch` should get the correct branch, otherwise that is a bug.

**Comment by scls19fr** [comment]
This is probably the kind of issue I'm also facing.

```
C:\Users\Admin-pc\.julia\dev\Documenter>julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0 (2018-08-08 06:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

(v0.7) pkg> add Documenter#fe/fix-parsing
  Updating registry at `C:\Users\Admin-pc\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/JuliaDocs/Documenter.jl.git`
 Resolving package versions...
  Updating `C:\Users\Admin-pc\.julia\environments\v0.7\Project.toml`
 [no changes]
  Updating `C:\Users\Admin-pc\.julia\environments\v0.7\Manifest.toml`
 [no changes]

(v0.7) pkg> ^C

julia> ^C

julia>

C:\Users\Admin-pc\.julia\dev\Documenter>git branch
* master
```

**Comment by fredrikekre** [comment]
`add`ed branches does not end up in `dev`

**Comment by Datseris** [comment]
> `add Package#branch` should get the correct branch, otherwise that is a bug.
It does, just tested it as well. Sorry for the off-topic comment!

**Comment by scls19fr** [comment]
How can I check that I'm running the "right" Documenter (ie from fe/fix-parsing branch)

**Comment by fredrikekre** [comment]
Ok, found a simple testcase that still fails on this branch. Will ping you when I have a new version that you can try.

**Comment by fredrikekre** [comment]
Okay, @Datseris and @scls19fr feel free to test the new version.

**Comment by scls19fr** [comment]
After you merge to master, I did

```
Pkg.rm("Documenter")
Pkg.devevlop("Documenter")
```

but I still facing #790

**Comment by KristofferC** [comment]
You might have to pull the newest version manually, there is a bug where develop fails to get the latest version.

**Comment by Datseris** [comment]
I can still confirm that on the current master this works for me.

**Comment by scls19fr** [comment]
Under Mac OS X now

```
$ cd ~/.julia/dev/Documenter
$ git pull
$ cd ~/.julia/dev/DataStructures/docs
$ julia make.jl
```

Minimal md file mentioned in https://github.com/JuliaDocs/Documenter.jl/issues/790#issue-350004634 saved with CRLF or LF as EOL still render badly

```
julia> dd = DefaultDict{AbstractString, Vector{Int}}(Vector{Int})
DefaultDict{AbstractString,Array{Int64,1},DataType} with 0 entries

┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0

julia> push!(dd["A"], 1)
1-element Array{Int64,1}:
 1

┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0

julia> push!(dd["B"], 2)
1-element Array{Int64,1}:
 2

┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0

julia> dd
DefaultDict{AbstractString,Array{Int64,1},DataType} with 2 entries:
  "B" => [2]
  "A" => [1]
```

**Comment by scls19fr** [comment]
Trying with an even simpler file

```
# Dict

```@repl
dd = Dict{AbstractString, Int}()

dd["A"] = 1

dd
```

(CRLF or LF)

rendered as

```
julia> dd = Dict{AbstractString, Int}()
Dict{AbstractString,Int64} with 0 entries

┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0

julia> dd["A"] = 1
1

┌ Warning: Deprecated syntax `underscores as an rvalue`.
└ @ none:0

julia> dd
Dict{AbstractString,Int64} with 1 entry:
  "A" => 1
```
