### PR TITLE
Turn docstring accordions from article-header into details-summary

### LINKED ISSUE #2772: Usability issue: click target for collapsing and expanding docstrings is "suboptimal"
This was originally reported to use by @johnabbott at https://github.com/oscar-system/Oscar.jl/issues/5273 and I've asked him to turn it into an issue here, but he seems to be busy with other stuff, so I am doing it now.

To reproduce, go to e.g. <https://docs.julialang.org/en/v1/base/base/#Getting-Around> and try to collapse and then expand the docstring for `Base.exit`. Try to figure out where you can click and where you can't.

It turns out clicking on the text does not work -- for "Base.exit" itself, I understand it (it's a link anchor), but I find it surprising that clicking on "— Function" also has no effect.

(Personally I also find the animation sluggish and distracting but that's probably just me, I prefer no or minimal animations for such things).

Looking at the implementation, it seems to rely on JavaScript, which may explain some other issues we have. E.g. on https://docs.oscar-system.org/stable/ we have all docstrings *collapsed* by default. This interacts badly with search: try searching e.g. for `is_quasisimple`. This leads to [this link](https://docs.oscar-system.org/stable/Groups/group_characters/#is_quasisimple-Tuple%7BOscar.GAPGroupCharacterTable%7D) -- at least for me, if I follow that link the scroll position ends up at the completely wrong spot.

---

Possible solution: have you considered using [`<details>` + `summary`](https://www.w3schools.com/tags/tag_details.asp) tags instead? That way one could eliminate the JavaScript (animations can still be done via CSS), and possibly solve both issues at once.

If there is general interest in trying such an approach out, I could ask @aaruni96 to look into doing experimentally (at least the "easy" part of changing the HTML generating code. CSS styling is another matter... but one step after the other).

### PR DESCRIPTION
**Pull request by aaruni96**
Fixes #2772

### CODE REVIEW

File: src/html/HTMLWriter.jl [hunk 1]
```diff
@@ -1854,14 +1854,13 @@ function domify(dctx::DCtx, mdast_node::Node, docsnode::Documenter.DocsNode)
     )
     push!(ctx.search_index, rec)
 
-    return article[".docstring"](
-        header(
-            a[".docstring-article-toggle-button.fa-solid.fa-chevron-down", :href => "javascript:;", :title => "Collapse docstring"],
-            a[".docstring-binding", :id => docsnode.anchor.id, :href => "#$(docsnode.anchor.id)"](code("$(docsnode.object.binding)")),
```
Comment (fingolfin) [inline src/html/HTMLWriter.jl:1907]: (First off: thanks for working on this!)

I think the `href` was here so that people could click on the name and the URL changes to include the href, thus making it possible to get a bookmarkable URL pointing directly at a specific docstring. Of course the downside is that clicking the text then does not expand/collapse the docstring; but perhaps that's not too bad?

Anyway, that's fine tuning, I fully understand this is a first prototype, and I do not mean to interfere with that, just point something out for consideration before a potential merge.

Comment (aaruni96) [reply src/html/HTMLWriter.jl:1907]: There were two `hrefs` in the original code, one for the anchor (which is preserved), and another which did weird and wonderful javascript things to make the `<article>` behave like an accordion. This is the one which I get rid of.

**Comment by aaruni96** [comment]
Current behavior:

All collapsible sections are collapsed by default. They toggle their state between expand/collapse if you click anywhere on the header, except if you click on the link, which expands the section and scrolls it to the top.

If you share a link with an anchor pointing to a specific section, that section is expanded and scrolled to the top.


I need help with both the javascript and the stylesheets.

The javascript I've added works, but I need advise on whether it should be the only thing in that file, and if to rename the file, and whether to edit some other thing if the file is renamed.

The CSS I've come up with more or less mimics the current style, but I can't figure out how to correctly include it in Documenter. For my tests, I have been manually modifying the CSS file generated by Documenter.

Possible todo: adding animation to the expand/collapse.

**Comment by Rahban1** [comment]
> The CSS I've come up with more or less mimics the current style, but I can't figure out how to correctly include it in Documenter

you can just run `make themes` on your terminal and the css will be included in Documenter

**Comment by fingolfin** [comment]
@Rahban1 I think that's not the core of @aaruni96's problem; it is where and how to properly put these changes into the various SCSS files?

@aaruni96 make sure to have a look at <assets/html/scss/documenter/components/_docstring.scss>

**Comment by aaruni96** [comment]
Thanks for the help. New question:

Should I `git add` the resulting files after running `make themes`  ?

**Comment by aaruni96** [comment]
Got rid of merge conflicts v/s the new master.

**Comment by Rahban1** [comment]
> Thanks for the help. New question:
> 
> 
> 
> Should I `git add` the resulting files after running `make themes`  ?

Yes

File: assets/html/js/metadata.js [hunk 2]
```diff
@@ -1,6 +1,6 @@
 // libraries: jquery
 // arguments: $
-
+/*
 $(document).ready(function () {
   let meta = $("div[data-docstringscollapsed]").data();
```
Comment (fingolfin) [inline assets/html/js/metadata.js]: My understanding based on what you just explained to me off-band is that this function dealt with scrolling the view port (which was meant to fix certain issues but never really worked well), and which is now unnecessary with your changes as the browser just does the right thing.

So I would suggest we just delete it!

**Comment by goerz** [comment]
In terms of how this looks visually, the animation speed, and the click targets for collapsing/uncollapsing, I think this is perfect.

I appreciate that a direct link to a docstring will always expand it. That seems like very desirable behavior.

But I think this will have to support the `CollapsedDocStrings` settings in the meta-block to allow to choose whether docstrings on a particular page are collapsed or expanded by default. I definitely write documentation that depends on particular docstrings being expanded by default.

Also, the global collapse/expand button in top right corner of the page will have to be made to work again.

I would consider breaking either one of those behaviors a semver-breaking change, so I think we'll have to find a way to get that to work again, with appropriate JS.

Other than that, this looks great!

**Comment by fingolfin** [comment]
I also just tried this on the OSCAR docs, and it is soooo much better, thank you @aaruni96 ! But of course @goerz also raises two relevant issues that need to be addressed. But I hope this won't too hard:
1. honoring `CollapsedDocStrings`: assuming this setting is known for each docstring at the time we generate the HTML, this could be handled by adding an `open="false"` or `'open="true"` attribute to the `<details>` element.
2. adding back some JavaScript to open or close all is also no major issue, see e.g. <https://stackoverflow.com/a/59742798> (and I am sure AI tools will also readily produce something).

File: assets/html/js/metadata.js (hunk 2 above)
Comment (fingolfin) [reply assets/html/js/metadata.js]: Aha this code is what drives the `documenter-article-toggle-button` which @goers mentioned. So this actually should be reactivated and modified suitably

File: assets/html/js/collapse.js [hunk 3]
```diff
@@ -1,78 +1,14 @@
...
-
-      parent
-        .children(".docstring-article-toggle-button")
-        .prop("title", articleToggleTitle);
-      parent.siblings("section").slideToggle();
-    });
-  },
-);
-
-$(document).on("click", ".docs-article-toggle-button", function (event) {
```
Comment (fingolfin) [inline assets/html/js/collapse.js:37]: This is the other part driving the button which collapses / expands all sections. So this would need to be retained in modified form to expand/collapse all

File: src/html/HTMLWriter.jl [hunk 4]
```diff
@@ -1854,13 +1854,13 @@ function domify(dctx::DCtx, mdast_node::Node, docsnode::Documenter.DocsNode)
     )
     push!(ctx.search_index, rec)
 
-    return article[".docstring"](
-        header(
-            a[".docstring-article-toggle-button.fa-solid.fa-chevron-down", :href => "javascript:;", :title => "Collapse docstring"],
```
Comment (mortenpi) [inline src/html/HTMLWriter.jl:1906]: Visually, it would be nice if we could retain the `fs-chevron-*` symbols for the triangle. Not sure if that's easy to do with CSS or not.

File: src/html/HTMLWriter.jl [hunk 5]
```diff
@@ -1854,13 +1854,13 @@ function domify(dctx::DCtx, mdast_node::Node, docsnode::Documenter.DocsNode)
     )
     push!(ctx.search_index, rec)
 
-    return article[".docstring"](
```
Comment (mortenpi) [inline src/html/HTMLWriter.jl:1904]: I wouldn't block on this, but once small concern I have is that `<details>` is probably not the right element here semantically. Docstrings have been wrapped in `<article>`-s, since they're generally important/main content, as opposed to a "widget from which the user can obtain additional information or controls".

I don't think we can really have a non-JS `<details>`-like behavior, but maybe we should at least retain an `<article>` element around the `<details>`?

File: CHANGELOG.md [hunk 6]
```diff
@@ -3,6 +3,12 @@
 The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
+## Unreleased
+
+### Changed
+
+* Changed the docstring block accordions from a custom implementation to HTML details+summary tag. ([#2773])
```
Comment (mortenpi) [inline CHANGELOG.md]:
```suggestion
* Changed the docstring block accordions from a custom implementation to HTML details+summary tag. ([#2772], [#2773])
```

**Review by mortenpi — CHANGES_REQUESTED** [review]
Agreed with @goerz's comments, plus a couple of small things from me. But generally I think this is great and the approach seems good to me.

I also think that getting rid of the animation is an improvement, since it makes the UX feel more snappy.

File: src/html/HTMLWriter.jl (hunk 5 above)
Comment (fingolfin) [reply src/html/HTMLWriter.jl:1904]: What purpose would the `<article>` serve? As a hint to screen readers? Wrapping the `<details>` in an `<article>` should be fine I guess, implementation-wise?

File: src/html/HTMLWriter.jl [hunk 7]
```diff
@@ -1854,16 +1854,16 @@ function domify(dctx::DCtx, mdast_node::Node, docsnode::Documenter.DocsNode)
...
-        header(
-            a[".docstring-article-toggle-button.fa-solid.fa-chevron-down", :href => "javascript:;", :title => "Collapse docstring"],
-            a[".docstring-binding", :id => docsnode.anchor.id, :href => "#$(docsnode.anchor.id)"](code("$(docsnode.object.binding)")),
+    return article(details[".docstring"](
```
Comment (fingolfin) [inline src/html/HTMLWriter.jl]: Needs runic reformatting.

File: assets/html/js/metadata.js [hunk 8]
```diff
@@ -3,25 +3,10 @@
 
 $(document).ready(function () {
   let meta = $("div[data-docstringscollapsed]").data();
-
-  if (meta?.docstringscollapsed) {
+  console.log(meta);
```
Comment (fingolfin) [inline assets/html/js/metadata.js]:
```suggestion
```

File: assets/html/js/metadata.js [hunk 9]
```diff
@@ -3,25 +3,10 @@
...
+  if (!meta.docstringscollapsed) {
```
Comment (fingolfin) [inline assets/html/js/metadata.js]: Could you please explain why `meta?.docstringscollapsed` changed to `!meta.docstringscollapsed` ? It's not at all clear to me :-(

File: src/html/HTMLWriter.jl [hunk 10]
```diff
@@ -1901,16 +1901,28 @@ function domify(dctx::DCtx, mdast_node::Node, docsnode::Documenter.DocsNode)
...
+            domify_doc(dctx, mdast_node)
+        )
     )
+    if get(getpage(ctx, navnode).globals.meta, :CollapsedDocStrings, false)
+        # if DocStringsCollapse = true in `@meta`
+        # shouldn't the check then be false?
+        # see line 1530 for original comment?
+        # collapse everything!
+        # do nothing, that is
+    else
```
Comment (fingolfin) [inline src/html/HTMLWriter.jl]:
```suggestion
    if !get(getpage(ctx, navnode).globals.meta, :CollapsedDocStrings, false)
        # if CollapsedDocStrings = true in `@meta`, do nothing, as the default
        # state is collapsed.
        # But if it is false, then set the `open` attribute to expand the
        # details+summary blocks.
    else
```

File: assets/html/js/metadata.js (hunk 9 above)
Comment (aaruni96) [reply assets/html/js/metadata.js]: I needed to add the negation because in the old way, everything was expanded by default, and would collapse if this property was true, and in the new way, everything is collapsed by default, and will be expanded if the property is set to false (or does not exist).

The `?.` went away as an accident and needs to be added back in.

File: src/html/HTMLWriter.jl (hunk 10 above)
Comment (aaruni96) [reply src/html/HTMLWriter.jl]: I don't actually understand what this `get()` does, but, in the behavior before my changes, we have (line 1570 after the rebase)

```julia
    if get(getpage(ctx, navnode).globals.meta, :CollapsedDocStrings, false)
        # if DocStringsCollapse = true in `@meta`, we let JavaScript click the
        # collapse button after that page has loaded.
        push!(meta_divs, div[Symbol("data-docstringscollapsed") => "true"]())
    end
```

So, if the `get()` thing is called with `false`, then somehow, that corresponds to `DocStringsCollapse` being set to true?

So, we really need to do nothing in the `if get(getpage(ctx, navnode).globals.meta, :CollapsedDocStrings, false)` clause, and need to expand all docstrings in the `else` case.

Comment (fingolfin) [reply src/html/HTMLWriter.jl]: The `get` method performs a dictionary lookup: the first argument `BLA.meta` is the dictionary, we look for the key `:CollapsedDocStrings`; if the key is absent, the default value `false` is substituted.

We then check the return value of `get`: if it returns `true`, then someone explicitly set `CollapsedDocStrings` to `true` and we should collapse things. If it returns `false`, then either it was set explicitly, or this is the default; in any case, we should explicitly expand things.

Comment (fingolfin) [reply src/html/HTMLWriter.jl]: We talked about it and part of the confusion was caused by me forgetting to delete the final `else` in my proposed code change 🤦 after we figured that out all became clear

**Review by fingolfin — APPROVED** [review]
Lovely. I just tried it with the Documenter documentation and as far as I could tell, everything works perfectly. Great job, @aaruni96 !

**Comment by fingolfin** [comment]
@goerz @mortenpi as far as I can tell all your concerns were addressed, but I'll wait a day or two in case  you want to complain (or let me know if you need more time).

**Comment by goerz** [comment]
Looks fantastic!
