### PR TITLE
Fix cleaning of the modules

### LINKED ISSUE #2673: Regression in Documenter@1.10.0
Hey, thanks for the work you are doing supporting Documenter, we recently got this error in our CI:
https://github.com/ReactiveBayes/RxInfer.jl/actions/runs/14166978246/job/39683505443

Since there were no changes on our side and this is a weekly CI run something must have been broken in Documenter, but the stacktrace isn't helpful 

```
[ Info: ExpandTemplates: expanding markdown templates.
ERROR: LoadError: MethodError: Cannot `convert` an object of type Nothing to an object of type String
The function `convert` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  convert(::Type{String}, !Matched::StringManipulation.Decoration)
   @ StringManipulation ~/.julia/packages/StringManipulation/inTre/src/decorations.jl:365
  convert(::Type{String}, !Matched::Base.JuliaSyntax.Kind)
   @ Base /cache/build/builder-amdci5-5/julialang/julia-release-1-dot-11/base/JuliaSyntax/src/kinds.jl:975
  convert(::Type{String}, !Matched::String)
   @ Base essentials.jl:461
  ...

Stacktrace:
  [1] top-level scope
    @ none:1
  [2] eval
    @ ./boot.jl:430 [inlined]
  [3] clear_module!(M::Module)
    @ Documenter ~/.julia/packages/Documenter/jyWLl/src/expander_pipeline.jl:9
  [4] clear_modules!(d::Dict{Symbol, Any})
    @ Documenter ~/.julia/packages/Documenter/jyWLl/src/expander_pipeline.jl:18
  [5] expand(doc::Documenter.Document)
    @ Documenter ~/.julia/packages/Documenter/jyWLl/src/expander_pipeline.jl:47
  [6] runner(::Type{Documenter.Builder.ExpandTemplates}, doc::Documenter.Document)
    @ Documenter ~/.julia/packages/Documenter/jyWLl/src/builder_pipeline.jl:224
  [7] dispatch(::Type{Documenter.Builder.DocumentPipeline}, x::Documenter.Document)
    @ Documenter.Selectors ~/.julia/packages/Documenter/jyWLl/src/utilities/Selectors.jl:170
  [8] #90
    @ ~/.julia/packages/Documenter/jyWLl/src/makedocs.jl:275 [inlined]
  [9] withenv(::Documenter.var"#90#92"{Documenter.Document}, ::Pair{String, Nothing}, ::Vararg{Pair{String, Nothing}})
    @ Base ./env.jl:265
 [10] #89
    @ ~/.julia/packages/Documenter/jyWLl/src/makedocs.jl:274 [inlined]
 [11] cd(f::Documenter.var"#89#91"{Documenter.Document}, dir::String)
    @ Base.Filesystem ./file.jl:112
 [12] makedocs(; debug::Bool, format::Documenter.HTMLWriter.HTML, kwargs::@Kwargs{draft::Bool, warnonly::Bool, modules::Vector{Module}, authors::String, sitename::String, pages::Vector{Pair{String, Any}}})
    @ Documenter ~/.julia/packages/Documenter/jyWLl/src/makedocs.jl:273
 [13] top-level scope
    @ ~/work/RxInfer.jl/RxInfer.jl/docs/make.jl:14
in expression starting at /home/runner/work/RxInfer.jl/RxInfer.jl/docs/make.jl:14
make: *** [Makefile:47: docs] Error 1
```

### PR DESCRIPTION
**Pull request by bvdmitri**
This PR attempts to fix #2673 . The problem is that the new cleaning functionality aggressively tries to assign `nothing` to all names defined in the module. It does check against `const`, but this isn't enough since users can write typed assignments, e.g. `a::String = "b"`. This would later cause problems when assigning `a` to `nothing`. This PR fixes it by wrapping the `@eval` in `try-catch` block and also adding this as an example in the tests.

### CODE REVIEW

File: src/expander_pipeline.jl [hunk 1]
```diff
@@ -6,7 +6,13 @@ function clear_module!(M::Module)
...
     for name in Base.invokelatest(names, M, all = true)
         if !isconst(M, name)
-            @eval M $name = $nothing
+            # see, e.g https://github.com/JuliaDocs/Documenter.jl/issues/2673
+            # it is not possible to set `nothing` to variables, which are strongly typed
+            # still attempt to set it, but ignore any errors
+            try
+                @eval M $name = $nothing
+            catch _
+            end
```
Comment (fredrikekre) [inline src/expander_pipeline.jl:15]: Perhaps a debug log message could be useful:
```suggestion
            catch err
                @debug "Could not clear variable `$name` by assigning `nothing`" err
            end
```

**Review by fredrikekre — APPROVED** [review]
If you update the version number in Project.toml we can make a quick release I think.

**Comment by bvdmitri** [comment]
So the tests failed on Julia 1.6 since there it was not allowed to use typed declarations for global variables. I changed the example block to use `@static` check. I've also updated the CHANGELOG.md and bumped the version

File: CHANGELOG.md [hunk 2]
```diff
@@ -3,6 +3,12 @@
 The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
+# Version [v1.10.1] - 2025-03-31
+
+## Fixed
+
+* Fixed a bug in the cleaning of `@example` blocks with `a::SomeType = somevalue` typed declarations. ([#2673, #2674])
```
Comment (fingolfin) [inline CHANGELOG.md:10]: Quick unimportant side-question to maintainers: is it usual to include the issue *and* PR here? I don't mind either way, but in my recent PRs I didn't do it, and wonder if I should have.

File: test/clear_module/src/index.md [hunk 3]
```diff
@@ -21,3 +21,33 @@ a = MyMutableStruct(1)
...
+```
+
+```@example example-2
+nothing = 1 # it is possible to use `nothing` as a variable name
+a = 2
+```
+
+```@example example-3
+nothing() = 3 # it is possible to use `nothing` as a function name
+a = nothing()
```
Comment (fingolfin) [inline test/clear_module/src/index.md:38]: Same question

File: test/clear_module/src/index.md [hunk 4]
```diff
@@ -21,3 +21,33 @@ a = MyMutableStruct(1)
...
+```
+
+```@example example-4
+@static if VERSION >= v"1.8"
+typed::String = "string" # it is possible to use `::` to specify the type of a variable
```
Comment (fingolfin) [inline test/clear_module/src/index.md:43]: Can we detect this (and how) to properly fix the issue (in addition to also having the try/catch)

**Review by fingolfin — APPROVED** [review]
Thank you

File: test/clear_module/src/index.md [hunk 5]
```diff
@@ -21,3 +21,33 @@ a = MyMutableStruct(1)
...
 it, which we can later test by observing the value of `Main.finalizer_count`.
+
+# Example blocks
+
+```@example example-1
+a = 1 # simple assignment
+```
+
+```@example example-2
+nothing = 1 # it is possible to use `nothing` as a variable name
```
[the remark this answers is not in the document]
Comment (bvdmitri) [reply test/clear_module/src/index.md:32]: It didn't cause an issue, but when trying to reduce MWE I was experimenting with different "weird" Julia expressions which might have potentially be the cause of the issue. At the end it had nothing to do with defining `nothing` but I put it as a safeguard against future regressions, but I agree with you that `$nothing` should already prevent that because it should refer to `Base.nothing`

File: test/clear_module/src/index.md (hunk 3 above)
Comment (bvdmitri) [reply test/clear_module/src/index.md:38]: Same answer as above :)

File: CHANGELOG.md (hunk 2 above)
Comment (bvdmitri) [reply CHANGELOG.md]: for consistency with other changes I only linked PR

Comment (bvdmitri) [reply CHANGELOG.md]: Something is that I still don't understand is that sometimes it is using a single `#` or double `##` to define a new version and it doesn't seem consistent, e.g.
```
# Version [v1.10.0] - 2025-03-31

...

## Version [v1.9.0] - 2025-03-17
``` 

I think it used to use `##` everywhere, but `1.10` didn't do that (accidentally) ? I leave the decision to maintainers. Thanks for reviewing my PR!

File: test/clear_module/src/index.md (hunk 5 above)
[the remark this answers is not in the document]
Comment (fingolfin) [reply test/clear_module/src/index.md:32]: OK Thanks! And I agree it is a good idea to out this test in

File: CHANGELOG.md (hunk 2 above)
Comment (asinghvi17) [reply CHANGELOG.md]: I usually see only PR numbers, or "Made changes X, Y and Z to fix issue #123 [#124]", where 123 is the issue and 124 is a PR.  But they are generally not together.

File: src/expander_pipeline.jl [hunk 6]
```diff
@@ -6,7 +6,14 @@ function clear_module!(M::Module)
...
     for name in Base.invokelatest(names, M, all = true)
         if !isconst(M, name)
-            @eval M $name = $nothing
+            # see, e.g https://github.com/JuliaDocs/Documenter.jl/issues/2673
+            # it is not possible to set `nothing` to variables, which are strongly typed
+            # still attempt to set it, but ignore any errors
+            try
+                @eval M $name = $nothing
+            catch err
+                @debug "Could not clear variable `$name` by assigning `nothing`" err
```
Comment (asinghvi17) [inline src/expander_pipeline.jl:15]:
```suggestion
                @debug "Could not clear variable `$name` from module `$M` by assigning `nothing`" err

File: CHANGELOG.md
Comment (asinghvi17) [inline CHANGELOG.md:1]: Seems I lost the commit message so commenting here - the Keep a Changelog format and previous Documenter versions all prescribe this format (h2 for versions, h3 for categories within versions).

**Review by asinghvi17 — APPROVED** [review]

**Review by mortenpi — APPROVED** [review]

**Comment by mortenpi** [comment]
Thank you! Release here: https://github.com/JuliaRegistries/General/pull/128124
