### PR TITLE
Pass `-g` option to `curl` in linkchecker

### LINKED ISSUE #2839: linkcheck fails on links containing `{}`
```
┌ Error: `curl -sI --proto =http,https,ftp,ftps -H 'accept-encoding: gzip, deflate, br' --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' 'https://clima.github.io/OceananigansDocumentation/stable/appendix/library/#Oceananigans.Models.NonhydrostaticModels.NonhydrostaticModel-Tuple{}' --max-time 10 -o /dev/null --write-out '%{http_code} %{url_effective} %{redirect_url}'` failed:
│   exception =
│    failed process: Process(`curl -sI --proto =http,https,ftp,ftps -H 'accept-encoding: gzip, deflate, br' --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' 'https://clima.github.io/OceananigansDocumentation/stable/appendix/library/#Oceananigans.Models.NonhydrostaticModels.NonhydrostaticModel-Tuple{}' --max-time 10 -o /dev/null --write-out '%{http_code} %{url_effective} %{redirect_url}'`, ProcessExited(3)) [3]
│
└ @ Documenter ~/.julia/packages/Documenter/HdXI4/src/utilities/utilities.jl:47
```
Looks like we need to escape the curly braces?
```console
% curl -sI --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:144.0) Gecko/20100101 Firefox/144.0' 'https://clima.github.io/OceananigansDocumentation/stable/appendix/library/#Oceananigans.Models.NonhydrostaticModels.NonhydrostaticModel-Tuple\{\}' --max-time 10 -o /dev/null --write-out '%{http_code} %{url_effective} %{redirect_url}'
200 https://clima.github.io/OceananigansDocumentation/stable/appendix/library/#Oceananigans.Models.NonhydrostaticModels.NonhydrostaticModel-Tuple{}
```

### PR DESCRIPTION
**Pull request by giordano**
This avoids `{}` (common in URLs including signatures of Julia methods) being interpreted as globbing.

Fix #2839.

### CODE REVIEW

**Comment by mortenpi** [comment]
LGTM. Could we please have

- a simple test here: https://github.com/JuliaDocs/Documenter.jl/blob/a9af48effeea2b23f7c3e4a6a97738bff467e57b/test/online/online_linkcheck.jl
- And a changelog entry?

File: test/online/online_linkcheck.jl [hunk 1]
```diff
@@ -33,6 +33,8 @@ server = HTTP.serve!(lincheck_server_handler, PORT)
             [Requires GITHUB_TOKEN](https://raw.githubusercontent.com/JuliaDocs/Documenter.jl/v1.0.0/Project.toml)
             [Does not support GITHUB_TOKEN](https://github.com/JuliaDocs/Documenter.jl/pulls)
             [May require GITHUB_TOKEN](https://github.com/JuliaDocs/Documenter.jl/pull/2729)
+
+            Use [`getindex`](https://docs.julialang.org/en/v1.12.1/base/arrays/#Base.getindex-Tuple{AbstractArray,%20Vararg{Any}}) to get one element of an array.
```
Comment (giordano) [inline test/online/online_linkcheck.jl:37]:
```console
% curl -sI -H 'accept-encoding: gzip, deflate, br' --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' 'https://docs.julialang.org/en/v1.12.1/base/arrays/#Base.getindex-Tuple{AbstractArray,%20Vararg{Any}}' --max-time 10 -o /dev/null --write-out '%{http_code} %{url_effective} %{redirect_url}'
% curl -g -sI -H 'accept-encoding: gzip, deflate, br' --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' 'https://docs.julialang.org/en/v1.12.1/base/arrays/#Base.getindex-Tuple{AbstractArray,%20Vararg{Any}}' --max-time 10 -o /dev/null --write-out '%{http_code} %{url_effective} %{redirect_url}'
200 https://docs.julialang.org/en/v1.12.1/base/arrays/#Base.getindex-Tuple{AbstractArray,%20Vararg{Any}}
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -3,6 +3,12 @@
 The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
+## Unreleased
+
+### Changed
+
+* The `-g` is now passed to `curl` when checking links, to disable globbing. ([#2839], [#2842])
```
Comment (fingolfin) [inline CHANGELOG.md]: Reading this, I am not sure how it would affect me as a user. Perhaps we can expand on it a bit, like so?
```suggestion
* The `-g` is now passed to `curl` when checking links, to disable globbing, which could cause undesirable behavior when checking links containing characters like for example `[`, `{`, `&` or `?`. ([#2839], [#2842])
```

**Comment by mortenpi** [comment]
FWIW, this should probably be just a bugfix?
