### PR TITLE
Report location of @docs blocks with parsing errors

### LINKED ISSUE #2426: Unhelpful error during ?template expansion?
I would have hoped to get a error message that points me back to where I made the mistake.

```
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: skipped.
[ Info: ExpandTemplates: expanding markdown templates.

ERROR: LoadError: UndefVarError: `ScopedValue` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
  [1] top-level scope
    @ none:1
  [2] eval
    @ ./boot.jl:428 [inlined]
  [3] runner(::Type{Documenter.Expanders.DocsBlocks}, node::MarkdownAST.Node{Nothing}, page::Documenter.Page, doc::Documenter.Document)
    @ Documenter ~/src/julia/doc/deps/packages/Documenter/1HwWe/src/expander_pipeline.jl:403
  [4] dispatch(::Type{Documenter.Expanders.ExpanderPipeline}, ::MarkdownAST.Node{Nothing}, ::Vararg{Any})
    @ Documenter.Selectors ~/src/julia/doc/deps/packages/Documenter/1HwWe/src/utilities/Selectors.jl:170
  [5] expand(doc::Documenter.Document)
    @ Documenter ~/src/julia/doc/deps/packages/Documenter/1HwWe/src/expander_pipeline.jl:22
  [6] runner(::Type{Documenter.Builder.ExpandTemplates}, doc::Documenter.Document)
    @ Documenter ~/src/julia/doc/deps/packages/Documenter/1HwWe/src/builder_pipeline.jl:222
  [7] dispatch(::Type{Documenter.Builder.DocumentPipeline}, x::Documenter.Document)
    @ Documenter.Selectors ~/src/julia/doc/deps/packages/Documenter/1HwWe/src/utilities/Selectors.jl:170
  [8] #83
    @ ~/src/julia/doc/deps/packages/Documenter/1HwWe/src/makedocs.jl:248 [inlined]
  [9] withenv(::Documenter.var"#83#85"{Documenter.Document}, ::Pair{String, Nothing}, ::Vararg{Pair{String, Nothing}})
    @ Base ./env.jl:257
 [10] #82
    @ ~/src/julia/doc/deps/packages/Documenter/1HwWe/src/makedocs.jl:247 [inlined]
 [11] cd(f::Documenter.var"#82#84"{Documenter.Document}, dir::String)
    @ Base.Filesystem ./file.jl:112
 [12] makedocs(; debug::Bool, format::Documenter.HTMLWriter.HTML, kwargs::@Kwargs{build::String, modules::Vector{Module}, clean::Bool, doctest::Bool, linkcheck::Bool, linkcheck_ignore::Vector{String}, checkdocs::Symbol, sitename::String, authors::String, pages::Vector{Any}, remotes::Dict{String, Tuple{Documenter.Remotes.GitHub, String}}})
    @ Documenter ~/src/julia/doc/deps/packages/Documenter/1HwWe/src/makedocs.jl:247
 [13] top-level scope
    @ ~/src/julia/doc/make.jl:371
in expression starting at /home/vchuravy/src/julia/doc/make.jl:371
```

### LINKED ISSUE #2805: Add dedicated tests for warnings produced by `@docerror`
I'd like a set up that makes it very easy and convenient to systematically add tests for `@docerror` warnings.  See e.g. <https://github.com/JuliaDocs/Documenter.jl/pull/2804/files#r2489443251> for motivation.

That is, this would run mini-tests that are focused on producing a specific warning/error, and verify that this warning/error and no other warning/error are shown.

A version of this already exist in a special case in `test/docsxref/make.jl`:
```julia
    captured = IOCapture.capture() do
        makedocs(; kwargs...)
    end
    @test isnothing(captured.value)
    @test contains(
        replace(captured.output, "\\src\\index" => "/src/index"),
        """
        ┌ Warning: Cannot resolve @ref for md"[`AbstractSelector`](@ref)" in docsxref/src/index.md.
        │ - No docstring found in doc for binding `Main.DocsReferencingMain.AbstractSelector`.
        │ - Fallback resolution in Main for `AbstractSelector` -> `Documenter.Selectors.AbstractSelector` is only allowed for fully qualified names
        """
    )
    @test contains(
        replace(captured.output, "\\src\\page" => "/src/page"),
        """
        ┌ Warning: Cannot resolve @ref for md"[`DocsReferencingMain.f`](@ref)" in docsxref/src/page.md.
        │ - Exception trying to find docref for `DocsReferencingMain.f`: unable to get the binding for `DocsReferencingMain.f` in module Documenter.Selectors
        │ - Fallback resolution in Main for `DocsReferencingMain.f` -> `Main.DocsReferencingMain.f` is only allowed for fully qualified names
        """
    )
```

But it would be really nice if we could make sure there are no other warnings/errors in there as well. E.g. if we find the warnings, then remove it from the captured output; and check if the remainder contains the words `error` or `warning` (ignoring case).

### PR DESCRIPTION
**Pull request by fingolfin**
In particular, show the precise location where the error occurred.

Resolves #2426

I tested it locally but it still needs a test. Will add one later.

UPDATE: tests added. More so, this now resolves #2805 in so far as it adds a framework for adding tests for warning messages. I've used it here to test the warnings I am improving here, and have a couple more ready for a follow-up PR. That said, it's not "done" in so far as it does not yet cover *all* kinds of warnings; but that seems to me more like an open-ended project anyway.

### CODE REVIEW

File: test/warnings/make.jl [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+        │   exception =
+        │    UndefVarError: `NonsenseTypeThatDoesNotExist` not defined in `Main`
+        │    Suggestion: check for spelling errors or missing imports.
+        └ @ Documenter
+        [ Info: CrossReferences: building cross-references.
+        [ Info: CheckDocument: running document checks.
+        [ Info: Populate: populating indices.
+        [ Info: RenderDocument: rendering document.
+        [ Info: HTMLWriter: rendering HTML pages.
+        """
```
Comment (fingolfin) [inline test/warnings/make.jl]: This test and the output here is more or less what I have in mind for addressing issue #2805. I'd imagine adding a bunch of additional `.md` files to deal with warnings in `@example`, `@repl`, etc. blocks, and beyond. 

The check here is perhaps too fragile, the Info messages before and after should perhaps not be part of the text as they might change over time (?) but for now it was convenient to have them.


I am actually wondering if it wouldn't be better to have this all be in a `jldoctest`, so that one can use `doctest=:fix` to update it for changes in the output (e.g. tweaked line numbers)
