### PR TITLE
Don't error on `@example`, `@eval`, `@repl` blocks which are empty / only contain comments / contain syntax errors

### LINKED ISSUE #2206: AssertionError: length(exs) == 2 * length(results)
I get the above assertion error with the following input, `fei2_classical.md`:

`````
```@meta
EditURL = "../../../examples/fei2_classical.jl"
```

````@example fei2_classical
# Calculating S
````

---

*This page was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*
`````

This input was generated by running Literate on the following `fei2_classical.jl` file:

```
## Calculating S
```

I would expect to get an error message rather than an assertion failure.

Full stack trace:

```
ERROR: AssertionError: length(exs) == 2 * length(results)
Stacktrace:
  [1] parseblock(code::String, doc::Documenter.Document, file::String; skip::Int64, keywords::Bool, raise::Bool, linenumbernode::LineNumberNode)
    @ Documenter ~/.julia/dev/Documenter/src/utilities/utilities.jl:172
  [2] parseblock
    @ Documenter ~/.julia/dev/Documenter/src/utilities/utilities.jl:135 [inlined]
  [3] #parseblock#18
    @ Documenter ~/.julia/dev/Documenter/src/documents.jl:62 [inlined]
  [4] runner(::Type{Documenter.Expanders.ExampleBlocks}, node::MarkdownAST.Node{Nothing}, page::Documenter.Page, doc::Documenter.Document)
    @ Documenter.Expanders ~/.julia/dev/Documenter/src/Expanders.jl:713
  [5] dispatch(::Type{Documenter.Expanders.ExpanderPipeline}, ::MarkdownAST.Node{Nothing}, ::Vararg{Any})
    @ Documenter.Selectors ~/.julia/dev/Documenter/src/utilities/Selectors.jl:170
  [6] expand(doc::Documenter.Document)
    @ Documenter.Expanders ~/.julia/dev/Documenter/src/Expanders.jl:44
  [7] runner(::Type{Documenter.Builder.ExpandTemplates}, doc::Documenter.Document)
    @ Documenter.Builder ~/.julia/dev/Documenter/src/Builder.jl:232
  [8] dispatch(::Type{Documenter.Builder.DocumentPipeline}, x::Documenter.Document)
    @ Documenter.Selectors ~/.julia/dev/Documenter/src/utilities/Selectors.jl:170
  [9] #41
    @ Documenter ~/.julia/dev/Documenter/src/makedocs.jl:237 [inlined]
 [10] withenv(::Documenter.var"#41#43"{Documenter.Document}, ::Pair{String, Nothing}, ::Vararg{Pair{String, Nothing}})
    @ Base ./env.jl:235
 [11] #40
    @ Documenter ~/.julia/dev/Documenter/src/makedocs.jl:236 [inlined]
 [12] cd(f::Documenter.var"#40#42"{Documenter.Document}, dir::String)
    @ Base.Filesystem ./file.jl:112
 [13] #makedocs#39
    @ Documenter ~/.julia/dev/Documenter/src/makedocs.jl:236 [inlined]
 [14] top-level scope
    @ REPL[180]:1
```

At the point of the failed assertion, these variables are defined:
```
code == "# Calculating S\n"
exs == Any[:(#= fei2_classical.md:1 =#)]
results == Any[]
```

### LINKED ISSUE #2731: Example blocks should not crash the whole build on parse errors
```
for k in keys
    k !in acceptable_keys && do_something()
end
```
is an example of code that does not parse correctly.  In an `@example` block

```
Warning: failed to parse exception in src/somefile.md
  exception = 
    ParseError:
    # Error @ none:16:15
        for (param, value) in params
    #             ┌──────────────────────────
            param !in default_keys && error(...)
    #────────────────────────────────────────────────────────────────────────┘ ── Expected `end`
ERROR: LoadError: AssertionError: Issue at #= somefile.md:109 =#:
Stacktrace:
  [1] parseblock(code::String, doc::Documenter.Document, file::String; skip::Int64, keywords::Bool, raise::Bool, linenumbernode::LineNumberNode)
    @ Documenter ~/.julia/packages/Documenter/iRt2s/src/utilities/utilities.jl:172
  [2] parseblock
    @ ~/.julia/packages/Documenter/iRt2s/src/utilities/utilities.jl:138 [inlined]
  [3] #parseblock#21
    @ ~/.julia/packages/Documenter/iRt2s/src/documents.jl:80 [inlined]
  [4] runner(::Type{Documenter.Expanders.ExampleBlocks}, node::MarkdownAST.Node{Nothing}, page::Documenter.Page, doc::Documenter.Document)
    @ Documenter ~/.julia/packages/Documenter/iRt2s/src/expander_pipeline.jl:851
  [5] dispatch(::Type{Documenter.Expanders.ExpanderPipeline}, ::MarkdownAST.Node{Nothing}, ::Vararg{Any})
    @ Documenter.Selectors ~/.julia/packages/Documenter/iRt2s/src/utilities/Selectors.jl:170
  [6] expand(doc::Documenter.Document)
    @ Documenter ~/.julia/packages/Documenter/iRt2s/src/expander_pipeline.jl:59
  [7] runner(::Type{Documenter.Builder.ExpandTemplates}, doc::Documenter.Document)
    @ Documenter ~/.julia/packages/Documenter/iRt2s/src/builder_pipeline.jl:224
  [8] dispatch(::Type{Documenter.Builder.DocumentPipeline}, x::Documenter.Document)
    @ Documenter.Selectors ~/.julia/packages/Documenter/iRt2s/src/utilities/Selectors.jl:170
  [9] #88
    @ ~/.julia/packages/Documenter/iRt2s/src/makedocs.jl:275 [inlined]
 [10] withenv(::Documenter.var"#88#90"{Documenter.Document}, ::Pair{String, Nothing}, ::Vararg{Pair{String, Nothing}})
    @ Base ./env.jl:265
 [11] #87
    @ ~/.julia/packages/Documenter/iRt2s/src/makedocs.jl:274 [inlined]
 [12] cd(f::Documenter.var"#87#89"{Documenter.Document}, dir::String)
    @ Base.Filesystem ./file.jl:112
 [13] makedocs(; debug::Bool, format::MarkdownVitepress, kwargs::@Kwargs{modules::Vector{Module}, authors::String, sitename::String, pages::Vector{Pair{String, Any}}, warnonly::Bool, clean::Bool})
    @ Documenter ~/.julia/packages/Documenter/iRt2s/src/makedocs.jl:273
 

Error: Process completed with exit code 1.
```

This should probably not completely crash?  (Example is sanitized)

### PR DESCRIPTION
**Pull request by fingolfin**
Fixes #2206
Fixes #2731

(I am kinda abusing the "warnings" test setup here; but it was natural to start there as I am familiar with it. But it's another reason to merge `test/warnings` and `test/doctests` into, say, `test/output_tests`, as discussed in #2819. I'll get to that eventually but for now this simply was the quickest way for me to get this done right now)

### CODE REVIEW

File: test/warnings/make.jl [hunk 1]
```diff
@@ -85,7 +92,14 @@ julia> WarningTests.run_warnings_test("at-eval")
 [ Info: SetupBuildDirectory: setting up build directory.
 [ Info: Doctest: running doctests.
 [ Info: ExpandTemplates: expanding markdown templates.
-┌ Warning: Invalid type of object in @eval in src/at-eval.md:5-7
+┌ Warning: failed to parse code block in build/src/at-eval.md:13-15
```
Comment (fingolfin) [inline test/warnings/make.jl]: The Windows tests stumbled over this, and what a good thing that is: `build/` shouldn't be there. Gotta investigate.

**Comment by asinghvi17** [comment]
Hilariously enough, I just got bit by this last night (Literate.jl breaks functions at comment lines...)

**Comment by fingolfin** [comment]
BTW I also had a version of this were I added a test for `@meta` with invalid content, but it had an hard error that I could not figure out; I'll put this into a follow-up

File: test/warnings/make.jl (hunk 1 above)
Comment (fingolfin) [reply test/warnings/make.jl]: Ah this is because the code in `Selectors.runner(::Type{Expanders.EvalBlocks}, ...` calling `parseblock` does this inside a `cd(page.workdir) do ... end` block. 

I see two solutions (and one might even implement both):
1. we could narrow the scope of this `cd` do-block to only wrap around the `Core.eval` call
2. we could change `page.source` to be an absolute path -- that would avoid any similar such issues at the root

I'll try 1. for now as this is much simpler and more local.

Comment (asinghvi17) [reply test/warnings/make.jl]: 1 sounds better, since it wouldn't risk causing issues for renderers that might need relative paths.

File: src/utilities/utilities.jl [hunk 2]
```diff
@@ -155,15 +155,14 @@ function parseblock(
         line = match(r"^(.*)\r?\n"m, SubString(code, cursor)).match
         keyword = Symbol(strip(line))
         (ex, ncursor) =
-        # TODO: On 0.7 Symbol("") is in Docs.keywords, remove that check when dropping 0.6
```
Comment (fingolfin) [inline src/utilities/utilities.jl:158]: Let' drop this Julia 0.6 workaround ;-)

File: src/expander_pipeline.jl [hunk 3]
```diff
@@ -724,55 +724,55 @@ function Selectors.runner(::Type{Expanders.EvalBlocks}, node, page, doc)
...
-        for (ex, str) in Documenter.parseblock(
-                x.code, doc, page; keywords = false, linenumbernode = linenumbernode
-            )
-            try
+    result = nothing
+    for (ex, str) in Documenter.parseblock(
+            x.code, doc, page; keywords = false, linenumbernode, lines
+        )
+        try
+            cd(page.workdir) do
```
Comment (mortenpi) [inline src/expander_pipeline.jl:732]: Was there a reason to flip this around? Won't this break any blocks that have a  `cd` somewhere in there?

Comment (fingolfin) [reply src/expander_pipeline.jl:732]: yes, the error locations were otherwise wrong (that was an old bug that has bothered me several times in the past).

But you are right, this breaks consecutive named doctests where one changes a directory and subsequent ones rely on that.

I'll prepare a PR restoring this, together with a test for that situation.

Comment (fingolfin) [reply src/expander_pipeline.jl:732]: See PR #2837
