### PR TITLE
Initialize empty branch if deploydocs can't find gh-pages

### LINKED ISSUE #361: Cannot checkout remote branch?
I'm setting up Documenter.jl for [my package](https://github.com/tlnagy/Crispulator.jl) and I get the following error:

```julia
WARNING: `HTML` is deprecated use `:html` for `format = ...`.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in _fmt(::Documenter.Formats.Format) at /home/travis/.julia/v0.5/Documenter/src/Formats.jl:54
 in #Document#5(::String, ::String, ::String, ::Documenter.Formats.Format, ::Bool, ::Bool, ::Bool, ::Symbol, ::Bool, ::Array{Module,1}, ::Array{Any,1}, ::Array{String,1}, ::String, ::String, ::String, ::Array{Any,1}, ::Type{T}) at /home/travis/.julia/v0.5/Documenter/src/Documents.jl:249
 in (::Core.#kw#Type)(::Array{Any,1}, ::Type{Documenter.Documents.Document}) at ./<missing>:0
 in #makedocs#1(::Bool, ::Array{Any,1}, ::Function) at /home/travis/.julia/v0.5/Documenter/src/Documenter.jl:158
 in (::Documenter.#kw##makedocs)(::Array{Any,1}, ::Documenter.#makedocs) at ./<missing>:0
 in include_from_node1(::String) at ./loading.jl:488
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/travis/.julia/v0.5/Crispulator/docs/make.jl, in expression starting on line 3
Documenter: setting up build directory.
Documenter: expanding markdown templates.
Documenter: building cross-references.
Documenter: running document checks.
 > checking for missing docstrings.
 > running doctests.
 > checking footnote links.
Documenter: populating indices.
Documenter: rendering document.
Documenter: setting up target directory.
Documenter: pushing new documentation to remote: github.com/tlnagy/Crispulator.jl.git:gh-pages.
Initialized empty Git repository in /tmp/tmpSr8F5J/.git/
ERROR: LoadError: could not checkout remote branch.
 in (::Documenter.##9#15{String,String,String})() at /home/travis/.julia/v0.5/Documenter/src/Documenter.jl:429
 in cd(::Documenter.##9#15{String,String,String}, ::String) at ./file.jl:59
 in withfile(::Documenter.##8#14{String,String,String,String}, ::String, ::String) at /home/travis/.julia/v0.5/Documenter/src/Documenter.jl:477
 in (::Documenter.##7#13{String,String,String,String,String,String,String,String,Bool})(::String) at /home/travis/.julia/v0.5/Documenter/src/Documenter.jl:408
 in mktempdir(::Documenter.##7#13{String,String,String,String,String,String,String,String,Bool}, ::String) at ./file.jl:286
 in (::Documenter.##6#12{String,String,String,Void,String,String,String,String,String,Bool})() at /home/travis/.julia/v0.5/Documenter/src/Documenter.jl:377
 in cd(::Documenter.##6#12{String,String,String,Void,String,String,String,String,String,Bool}, ::String) at ./file.jl:59
 in #deploydocs#4(::String, ::String, ::String, ::String, ::String, ::String, ::String, ::String, ::Void, ::Void, ::Documenter.#deploydocs) at /home/travis/.julia/v0.5/Documenter/src/Documenter.jl:368
 in (::Documenter.#kw##deploydocs)(::Array{Any,1}, ::Documenter.#deploydocs) at ./<missing>:0
 in include_from_node1(::String) at ./loading.jl:488
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/travis/.julia/v0.5/Crispulator/docs/make.jl, in expression starting on line 13
```

It builds fine locally. I believe I set up all the keys properly.

### PR DESCRIPTION
**Pull request by iamed2**
This fixes #361 by creating a blank orphan branch if the deploy branch (usually "gh-pages") doesn't exist yet.

The alternative is including a note in the docs on how to create an push the initial empty branch.

### CODE REVIEW

File: src/Documenter.jl [hunk 1]
```diff
@@ -428,8 +428,15 @@ function deploydocs(;
...
-                        success(`git checkout -b $branch upstream/$branch`) ||
-                            error("could not checkout remote branch.")
+                        branch_exists = success(`git checkout -b $branch upstream/$branch`)
+
+                        if !branch_exists
+                            Utilities.log("assuming $branch doesn't exist yet; creating a new one.")
+                            success(`git checkout --orphan $branch`) ||
+                                error("could not create new empty branch.")
+                            success(`git rm -rf .`) ||
+                                error("could not clean up new empty branch working tree.")
```
Comment (omus) [inline src/Documenter.jl]: Maybe you should make an initial empty commit here?
```
git commit --allow-empty -m "initial empty commit"
```

**Comment by mortenpi** [comment]
Just a friendly reminder about this open PR :smile:

**Comment by iamed2** [comment]
Right! I'll take a look at this again.

File: src/Documenter.jl (hunk 1 above)
Comment (iamed2) [inline src/Documenter.jl]: We found that the empty commit made it harder to view and manipulate the git repo after. I don't think it hurts to add it in.

I wanted to be safe, but given the state of the surrounding code you're right that I can get rid of that `git rm`.

**Comment by iamed2** [comment]
Updated :)

File: src/Documenter.jl (hunk 1 above)
Comment (mortenpi) [inline src/Documenter.jl]: You mean not having the empty commit I presume?

Comment (iamed2) [inline src/Documenter.jl]: Yes, sorry

**Comment by mortenpi** [comment]
I took the liberty of rebasing, squashing and adding a few notes to the doc. Will merge when the tests finish. Thanks for the contribution!

**Comment by iamed2** [comment]
You're welcome, thanks for reminding me!
