### PR TITLE
Fix Utilities.submodules for module aliases

### LINKED ISSUE #851: Module aliases confuse Utilities.submodules
```julia
julia> module M1
       using LinearAlgebra
       end
Main.M1

julia> module M2
       using LinearAlgebra
       const LA = LinearAlgebra
       end
Main.M2

julia> using Documenter

julia> Documenter.Utilities.submodules(M1)
Set(Module[Main.M1])

julia> Documenter.Utilities.submodules(M2)
Set(Module[LinearAlgebra.BLAS, Main.M2, LinearAlgebra, LinearAlgebra.LAPACK])
```

This is causing a lot of spurious doc check "docstrings potentially missing" warnings for me.

### PR DESCRIPTION
**Pull request by tkoolen**
Fix #851

### CODE REVIEW

File: test/utilities.jl [hunk 1]
```diff
@@ -35,6 +35,17 @@ export OuterModule
 end
 end
 
+module ModuleWithAlias
+using LinearAlgebra
```
Comment (fredrikekre) [inline test/utilities.jl]: Create another test module instead? I believe this will pull in `LinearAlgebra` and `Random` as dependencies, which is not optimal.

Comment (tkoolen) [reply test/utilities.jl]: Done. I do think there should be a module that's its own parent as a test case, so I'm using `Main` for that now.

**Comment by mortenpi** [comment]
LGTM, thanks!
