### PR TITLE
Assume branch *is* from fork when not possible to verify.

### LINKED ISSUE #1961: CI failures when trying to push a doc preview
We've started seeing some CI Documentation failures recently in Trixi.jl. These failures occur when trying to push a Documentation preview where the PR comes from a fork and not the main repository (for example, https://github.com/trixi-framework/Trixi.jl/actions/runs/3195919016/jobs/5217171204#step:6:1244). 

I'm not sure if this was due to changes in Documenter.jl (the most recent version v0.27.23 was released before we started seeing these failures), but is there a reason that these CI failures started happening recently?

### LINKED ISSUE #1965: CI failures, preview related (in pull requests, not on master)
Maybe related to https://github.com/JuliaDocs/Documenter.jl/issues/1961, as discussed on slack, we have also the following curl error, setting `JULIA_DEBUG=Documenter` provides the following stacktrace:
```julia
┌ Debug: Running CURL led to an exception:
│   exception =
│    failed process: Process(`curl -s -S GET -H 'Authorization: token ***' -H 'User-Agent: Documenter.jl' -H 'Content-Type: application/json' --fail https://api.github.com/repos/JuliaPlots/PlotDocs.jl/pulls/306`, ProcessExited(1)) [1]
│    
│    Stacktrace:
│      [1] pipeline_error
│        @ ./process.jl:565 [inlined]
│      [2] run(::Base.CmdRedirect; wait::Bool)
│        @ Base ./process.jl:480
│      [3] run
│        @ ./process.jl:477 [inlined]
│      [4] run_and_capture(cmd::Cmd)
│        @ Documenter ~/.julia/packages/Documenter/yf96B/src/deployconfig.jl:546
│      [5] verify_github_pull_repository(repo::String, prnr::Int64)
│        @ Documenter ~/.julia/packages/Documenter/yf96B/src/deployconfig.jl:523
│      [6] deploy_folder(cfg::Documenter.GitHubActions; repo::String, repo_previews::String, branch::String, branch_previews::String, devbranch::String, push_preview::Bool, devurl::String, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│        @ Documenter ~/.julia/packages/Documenter/yf96B/src/deployconfig.jl:366
│      [7] deploydocs(; root::String, target::String, dirname::String, repo::String, branch::String, repo_previews::String, branch_previews::String, deps::Nothing, make::Nothing, devbranch::Nothing, devurl::String, versions::Vector{Any}, forcepush::Bool, deploy_config::Documenter.GitHubActions, push_preview::Bool, archive::Nothing)
│        @ Documenter ~/.julia/packages/Documenter/yf96B/src/Documenter.jl:553
│      [8] top-level scope
│        @ ~/work/PlotDocs.jl/PlotDocs.jl/docs/make.jl:176
│      [9] include(mod::Module, _path::String)
│        @ Base ./Base.jl:419
│     [10] exec_options(opts::Base.JLOptions)
│        @ Base ./client.jl:303
│     [11] _start()
│        @ Base ./client.jl:522
└ @ Documenter ~/.julia/packages/Documenter/yf96B/src/deployconfig.jl:530
┌ Info: Deployment criteria for deploying preview build from GitHub Actions:
│ - ✔ ENV["GITHUB_REPOSITORY"]="JuliaPlots/PlotDocs.jl" occurs in repo="github.com/JuliaPlots/PlotDocs.jl.git"
│ - ✔ ENV["GITHUB_REF"] corresponds to a PR number
│ - ✔ PR originates from the same repository
│ - ✔ `push_preview` keyword argument to deploydocs is `true`
│ - ✔ ENV["GITHUB_ACTOR"] exists and is non-empty
│ - ✔ ENV["GITHUB_TOKEN"] exists and is non-empty
└ Deploying: ✔
```

The workflow was working before, and suddenly stopped to work. The same workflow passes on master, but fails in `PRs`.

What appears to have changed is this:

**[working](https://github.com/JuliaPlots/PlotDocs.jl/actions/runs/3014993369/jobs/4845907624#step:5:6) - 1 month ago - PR**
```
   bash docs/ci_build.sh
  shell: /usr/bin/bash -e {0}
  env:
    PYTHON: 
    DOCUMENTER_KEY: ***
    GITHUB_TOKEN: ***
```

The `DOCUMENTER_KEY` secret is passed.

**[failing](https://github.com/JuliaPlots/PlotDocs.jl/actions/runs/3207002459/jobs/5241422925) - yesterday - PR**
```
   bash docs/ci_build.sh
  shell: /usr/bin/bash -e {0}
  env:
    ARTIFACTS_PATH: ~/.julia/artifacts
    PACKAGES_PATH: ~/.julia/packages
    REGISTRIES_PATH: 
    PYTHON: 
    GITHUB_TOKEN: ***
    DOCUMENTER_KEY: 
`DOCUMENTER_KEY` is missing
```

EDIT: see https://github.com/JuliaDocs/Documenter.jl/issues/1965#issuecomment-1272406085 logs instead.

The `DOCUMENTER_KEY` seems to have disappeared about a month ago in other PRs [log](https://github.com/JuliaPlots/PlotDocs.jl/actions/runs/3016418409/jobs/4850039801#step:5:6): the secret is now blank (and we have a flag `DOCUMENTER_KEY is missing` triggered by our [script](https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/ci_build.sh#L6)).

I know that https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow says:
```
Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
```

However, this worked before. So is it a change in `github` permissions ? What could be a workaround to this ?

### PR DESCRIPTION
**Pull request by fredrikekre**
This patch changes the default assumption when verifying if a pull request is coming from a branch or not from true to false.

Fixes #1961, fixes #1965, closes #1966.

### CODE REVIEW

**Comment by fredrikekre** [comment]
https://github.com/JuliaDocs/Documenter.jl/pull/1969/files?w=1 for review.

File: src/deployconfig.jl [hunk 1]
```diff
@@ -508,27 +508,28 @@ function post_github_status(type::S, deploydocs_repo::S, sha::S, subfolder=nothi
 end
 
 function verify_github_pull_repository(repo, prnr)
+    github_token = get(ENV, "GITHUB_TOKEN", nothing)
+    if github_token === nothing
+        @warn "Unable to verify if PR comes from destination repository -- assuming it doesn't."
```
Comment (mortenpi) [inline src/deployconfig.jl:513]:
```suggestion
        @warn "GITHUB_TOKEN is missing, unable to verify if PR comes from destination repository -- assuming it doesn't."
```

**Review by mortenpi — APPROVED** [review]
LGTM. Also, nice job sleuthing the GR stuff.

1. I think this could use a brief CHANGELOG note, since it slightly changes behavior.
2. Could we also add a small note to the docts, something like
   > On GitHub Actions, `GITHUB_TOKEN` must be present for previews to work, even if `DOCUMENTER_KEY` is being used to deploy."

   to
 

   
 https://github.com/JuliaDocs/Documenter.jl/blob/2d020135d76d2f91c2e031cb90027a47f530b322/src/Documenter.jl#L474-L478
